name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup
        uses: ./tooling/github/setup
    - name: Install Playwright Browsers
      run: pnpm playwright:init
    - name: Run Playwright tests for our nextjs app
      run: pnpm test:e2e:nextjs
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30